Create database Hospital_db;
use Hospital_db;

create table patients (
patient_id varchar(10) primary key,
first_name varchar(50),
last_name varchar(50),
gender varchar (10),
date_of_birth date,
blood_type varchar(5),
city varchar(50),
contact_number varchar(20),
email varchar(100),
registration_date date,
insurance_provider varchar(50),
insurance_number varchar(50),
medical_condition varchar(50),
admission_type varchar(20),
medication varchar(50),
age int,
age_group varchar(10)
);
select	count(*) from patients;

create table appointments (
appointment_id varchar(10) primary key,
patinet_id varchar(10),
doctor_id varchar(10),
appointment_date date ,
appointment_time time,
reason_for_visit varchar(50),
status varchar(20),
admission_type varchar(20),
test_result varchar(20)
);
select count(*) from appointments;

create table doctors (
    doctor_id varchar(10) primary key,
    first_name varchar(50),
    last_name varchar(50),
    gender varchar(10),
    specialization varchar(50),
    years_experience int,
    email varchar(50),
    contact_number varchar(20),
    hospital_branch varchar(50),
    consultation_fee decimal(10,2),
    rating decimal(3,1),
    full_name varchar(100)
);

select count(*) from doctors;

CREATE TABLE billing (
    bill_id VARCHAR(10) PRIMARY KEY,
    patient_id VARCHAR(10),
    treatment_id VARCHAR(10),
    bill_date DATE,
    base_amount DECIMAL(10,2),
    discount_percent DECIMAL(5,2),
    final_amount DECIMAL(10,2),
    payment_method VARCHAR(20),
    payment_status VARCHAR(20),
    insurance_claim DECIMAL(10,2),
    amount_due DECIMAL(10,2)
);
select count(*) from billing;


create table treatments (
    treatment_id varchar(10) primary key,
    patient_id varchar(10),
    doctor_id varchar(10),
    appointment_id varchar(10),
    treatment_type varchar(50),
    description varchar(200),
    cost decimal(10,2),
    duration_minutes decimal(10,2),
    treatment_date date,
    outcome varchar(20)
);

select count(*) from treatments ;

show tables;


select * from appointments;
select * from patients;
select * from doctors;
select * from treatments;
select * from billing;
-------------------------------------- Business Problems -----------------------------------

-- List all diabetic patients ordered by age (oldest first)
select patient_id,first_name,last_name,gender,city,age,age_group,medical_condition
from patients
where medical_condition = "Diabetes Type 2"
order by age desc;

select count(*) from patients 
where medical_condition = "Diabetes Type 2";

-- Find the Top 10 patients with the highest medical bills
select patient_id , final_amount,payment_method,payment_status
from billing
order by final_amount desc
limit 10;
                   -- Or--
select p.patient_id,p.first_name,p.last_name,b.final_amount,b.payment_method,b.payment_status 
from patients p 
join billing b
on p.patient_id = b.patient_id
order by b.final_amount desc
limit 10;

-- Find the total number of patients in each city, ordered by highest count 
select count(patient_id) as Total_patients , city 
from patients 
group by city 
order by Total_patients desc;

-- Find all unique medical conditions treated in the hospital
select distinct medical_condition
from patients
order by medical_condition asc ;
 
-- Find doctors who have performed more than 120 treatments
select doctor_id, count(treatment_id) as Total_treatments 
from treatments 
group by doctor_id
having count(treatment_id)>120
order by Total_treatments desc;

-- Show patient name with their appointment details
select
 p.patient_id,p.first_name,p.last_name,p.medical_condition,
 a.appointment_date,a.reason_for_visit,a.status,a.test_result 
 from patients p 
 join appointments a
 on p.patient_id = a.patient_id
 order by a.appointment_date desc;
 
 select * from appointments;
 select * from patients;
 alter table appointments rename column patinet_id to patient_id ;
 describe  appointments;
 
 -- Show doctor name, patient name and their treatment cost together
 select
 d.full_name as doctor_name,
 concat(P.first_name ," ", p.last_name) as patient_name,
 -- p.first_name , p.last_name,
 p.medical_condition,
 t.treatment_type, t.cost , t.outcome 
 from treatments t
 join patients p
  on p.patient_id = t.patient_id
 join doctors d 
  on d.doctor_id = t.doctor_id
 order by t.cost desc;

-- Find total revenue generated by each payment method
select
payment_method,
count(bill_id) , round(sum(final_amount),2) as Total_revenue
from billing
group by payment_method
order by Total_revenue desc;

-- Find total number of appointments in year 2022 and 2023 separately
select 
count(appointment_id),
 year(appointment_date) as year 
 from appointments
 where appointment_date between "2022-01-01" and "2023-12-31"
 group by year(appointment_date)
 order by year asc;
 
 -- Find all patients whose bill amount is higher than the average bill amount
 select 
 p.first_name,p.last_name,p.medical_condition ,
 b.final_amount,b.payment_status
 from patients p
 join billing b
  on p.patient_id = b.patient_id
  where b.final_amount > (
    select avg(final_amount)
	from billing )
order by b.final_amount desc ;

-- Categorize each bill as Low, Medium or High value
select bill_id,patient_id,final_amount,payment_status,
case
	when final_amount < 3000 then "Low"
    when final_amount between 3000 and 7000 then "Medium"
    else "High"
    end as bill_category 
    from billing
    order by final_amount desc;
  
-- Find total revenue generated by each doctor
select d.doctor_id,d.full_name,d.specialization,
count(t.treatment_id) as total_treatments,round(sum(t.cost),2) as total_revenue
from doctors d
join treatments t 
	on d.doctor_id = t.doctor_id
group by d.doctor_id,d.full_name,d.specialization
order  by total_revenue desc;

-- Find the most expensive treatment among all completed appointments
select concat(p.first_name," ",p.last_name) as patient_name,
d.full_name as doctor_name,
a.status,
t.treatment_type,t.cost,t.outcome
from treatments t
join patients p
	on t.patient_id = p.patient_id
join doctors d
	on t.doctor_id = d.doctor_id
join appointments a
	on t.appointment_id = a.appointment_id
where a.status = "Completed"
order by t.cost desc
limit 10;

-- Compare month-wise revenue between 2022 and 2023
select 
year(bill_date) as year,
month(bill_date) as month,
monthname(bill_date) as month_name,
round(sum(final_amount),2) as total_revenue
from billing
where year(bill_date) in (2022,2023)
group by year(bill_date),month(bill_date),monthname(bill_date)
order by year Asc;

-- Create a view for doctor performance summary
create view doctors_performance as
select 
d.doctor_id,d.full_name as doctor_name,d.specialization,d.rating,d.years_experience,
count(t.treatment_id) as Total_treatments,round(sum(t.cost),2)as total_revenue,round(avg(t.cost),2)as avg_treatment_cost
from doctors d
join treatments t 
	on d.doctor_id = t.doctor_id
group by d.doctor_id,d.full_name,d.specialization,d.rating,d.years_experience
order by total_revenue desc; 
select * from doctors_performance;


-- Get all details of a patient by their patient ID
DELIMITER //

create procedure GetPatientDetails(in p_id varchar(20))
begin
    select 
        p.patient_id,p.first_name,p.last_name,p.gender,p.age,p.medical_condition,p.insurance_provider,
        a.appointment_date,a.status,a.reason_for_visit,
        b.final_amount,b.payment_status
    from patients p
    left join appointments a ON p.patient_id = a.patient_id
    left join billing b ON p.patient_id = b.patient_id
    where p.patient_id = p_id;
end //

DELIMITER ;

call GetPatientDetails("p0001");

-- Get all appointments of a specific doctor
DELIMITER //

create procedure GetDoctorAppointments(in d_id varchar(10))
begin
    select 
        a.appointment_id,
        a.appointment_date,
        a.status,
        a.reason_for_visit,
        p.first_name,
        p.last_name
    from appointments a
    join patients p 
        on a.patient_id = p.patient_id
    where a.doctor_id = d_id;
end //

DELIMITER ;
call GetDoctorAppointments ("D001");

select * from doctors_performance;
select * from appointments;
select *from treatments;


    